version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: todo_db
    ports:
      - "5436:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
